env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 80
    lines: 24

  padding:
    x: 0
    y: 0

  dynamic_padding: true
  # decorations: buttonless
  startup_mode: Windowed
  title: Terminal

scrolling:
  history: 10000
  multiplier: 3

shell:
  program: /usr/local/bin/tmux
  args:
    # - -l
    # - -u
    - new-session
    - -A
    - -D
    - -s
    - main

font:
  normal:
    family: Hack
    style: Regular
  bold:
    family: Hack
    style: Bold
  italic:
    family: Hack
    style: Italic

  #  scale_with_dpi: true
  use_thin_strokes: true

  size: 13
  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

colors:
  # Default colors
  primary:
    background: '0x002b36'
    foreground: '0x839496'

  # Normal colors
  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'

  # Bright colors
  bright:
    black:   '0x002b36'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'

#colors:
#  primary:
#    # hard contrast background - '#1d2021'
#    background: &gruvbox_dark_bg "#1d2021"
#    # soft contrast background - '#32302f'
#    foreground: "#fbf1c7"
#    bright_foreground: "#f9f5d7"
#    dim_foreground: "#f2e5bc"
#  cursor:
#    text: CellBackground
#
#    cursor: CellForeground
#  vi_mode_cursor:
#    text: CellBackground
#    cursor: CellForeground
#  selection:
#    text: CellBackground
#    background: CellForeground
#  bright:
#    black: "#928374"
#    red: "#fb4934"
#    green: "#b8bb26"
#    yellow: "#fabd2f"
#    blue: "#83a598"
#    magenta: "#d3869b"
#    cyan: "#8ec07c"
#    white: "#ebdbb2"
#  normal:
#    black: *gruvbox_dark_bg
#    red: "#cc241d"
#    green: "#98971a"
#    yellow: "#d79921"
#    blue: "#458588"
#    magenta: "#b16286"
#    cyan: "#689d6a"
#    white: "#a89984"
#  dim:
#    black: "#32302f"
#    red: "#9d0006"
#    green: "#79740e"
#    yellow: "#b57614"
#    blue: "#076678"
#    magenta: "#8f3f71"
#    cyan: "#427b58"
#    white: "#928374"
#  # indexed_colors: []

bell:
  animation: EaseOutExpo
  duration: 0
  color: "0xffffff"

window.opacity: 1.0

selection:
  semantic_escape_chars: ",?`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style: Block

live_config_reload: true

mouse:
  hide_when_typing: true

url:
  launcher:
    program: open

key_bindings:
  # # Vi Mode
  # - {
  #     key: Space,
  #     mods: Shift|Control,
  #     mode: Vi|~Search,
  #     action: ScrollToBottom,
  #   }
  # - { key: Space, mods: Shift|Control, mode: ~Search, action: ToggleViMode }
  # - { key: Escape, mode: Vi|~Search, action: ClearSelection }
  # - { key: I, mode: Vi|~Search, action: ScrollToBottom }
  # - { key: I, mode: Vi|~Search, action: ToggleViMode }
  # - { key: C, mods: Control, mode: Vi|~Search, action: ToggleViMode }
  # - { key: Y, mods: Control, mode: Vi|~Search, action: ScrollLineUp }
  # - { key: E, mods: Control, mode: Vi|~Search, action: ScrollLineDown }
  # - { key: G, mode: Vi|~Search, action: ScrollToTop }
  # - { key: G, mods: Shift, mode: Vi|~Search, action: ScrollToBottom }
  # - { key: B, mods: Control, mode: Vi|~Search, action: ScrollPageUp }
  # - { key: F, mods: Control, mode: Vi|~Search, action: ScrollPageDown }
  # - { key: U, mods: Control, mode: Vi|~Search, action: ScrollHalfPageUp }
  # - { key: D, mods: Control, mode: Vi|~Search, action: ScrollHalfPageDown }
  # - { key: Y, mode: Vi|~Search, action: Copy }
  # - { key: Y, mode: Vi|~Search, action: ClearSelection }
  # - { key: Copy, mode: Vi|~Search, action: ClearSelection }
  # - { key: V, mode: Vi|~Search, action: ToggleNormalSelection }
  # - { key: V, mods: Shift, mode: Vi|~Search, action: ToggleLineSelection }
  # - { key: V, mods: Control, mode: Vi|~Search, action: ToggleBlockSelection }
  # - { key: V, mods: Alt, mode: Vi|~Search, action: ToggleSemanticSelection }
  # - { key: Return, mode: Vi|~Search, action: Open }
  # - { key: K, mode: Vi|~Search, action: Up }
  # - { key: J, mode: Vi|~Search, action: Down }
  # - { key: H, mode: Vi|~Search, action: Left }
  # - { key: L, mode: Vi|~Search, action: Right }
  # - { key: Up, mode: Vi|~Search, action: Up }
  # - { key: Down, mode: Vi|~Search, action: Down }
  # - { key: Left, mode: Vi|~Search, action: Left }
  # - { key: Right, mode: Vi|~Search, action: Right }
  # - { key: Key0, mode: Vi|~Search, action: First }
  # - { key: Key4, mods: Shift, mode: Vi|~Search, action: Last }
  # - { key: Key6, mods: Shift, mode: Vi|~Search, action: FirstOccupied }
  # - { key: H, mods: Shift, mode: Vi|~Search, action: High }
  # - { key: M, mods: Shift, mode: Vi|~Search, action: Middle }
  # - { key: L, mods: Shift, mode: Vi|~Search, action: Low }
  # - { key: B, mode: Vi|~Search, action: SemanticLeft }
  # - { key: W, mode: Vi|~Search, action: SemanticRight }
  # - { key: E, mode: Vi|~Search, action: SemanticRightEnd }
  # - { key: B, mods: Shift, mode: Vi|~Search, action: WordLeft }
  # - { key: W, mods: Shift, mode: Vi|~Search, action: WordRight }
  # - { key: E, mods: Shift, mode: Vi|~Search, action: WordRightEnd }
  # - { key: Key5, mods: Shift, mode: Vi|~Search, action: Bracket }
  # - { key: Slash, mode: Vi|~Search, action: SearchForward }
  # - { key: Slash, mods: Shift, mode: Vi|~Search, action: SearchBackward }
  # - { key: N, mode: Vi|~Search, action: SearchNext }
  # - { key: N, mods: Shift, mode: Vi|~Search, action: SearchPrevious }

  # # Search Mode
  # - { key: Return, mode: Search|Vi, action: SearchConfirm }
  # - { key: Escape, mode: Search, action: SearchCancel }
  # - { key: C, mods: Control, mode: Search, action: SearchCancel }
  # - { key: U, mods: Control, mode: Search, action: SearchClear }
  # - { key: W, mods: Control, mode: Search, action: SearchDeleteWord }
  # - { key: P, mods: Control, mode: Search, action: SearchHistoryPrevious }
  # - { key: N, mods: Control, mode: Search, action: SearchHistoryNext }
  # - { key: Up, mode: Search, action: SearchHistoryPrevious }
  # - { key: Down, mode: Search, action: SearchHistoryNext }
  # - { key: Return, mode: Search|~Vi, action: SearchFocusNext }
  # - { key: Return, mods: Shift, mode: Search|~Vi, action: SearchFocusPrevious }

  # # (macOS only)
  # - { key: K, mods: Command, mode: ~Vi|~Search, chars: "\x0c" }
  # - { key: K, mods: Command, mode: ~Vi|~Search, action: ClearHistory }
  # - { key: Key0, mods: Command, action: ResetFontSize }
  # - { key: Equals, mods: Command, action: IncreaseFontSize }
  # - { key: Plus, mods: Command, action: IncreaseFontSize }
  # - { key: NumpadAdd, mods: Command, action: IncreaseFontSize }
  # - { key: Minus, mods: Command, action: DecreaseFontSize }
  # - { key: NumpadSubtract, mods: Command, action: DecreaseFontSize }
  # - { key: V, mods: Command, action: Paste }
  # - { key: C, mods: Command, action: Copy }
  # - { key: C, mods: Command, mode: Vi|~Search, action: ClearSelection }
  # - { key: H, mods: Command, action: Hide }
  # - { key: M, mods: Command, action: Minimize }
  # - { key: Q, mods: Command, action: Quit }
  # - { key: W, mods: Command, action: Quit }
  # - { key: N, mods: Command, action: SpawnNewInstance }
  # - { key: F, mods: Command|Control, action: ToggleFullscreen }
  # - { key: F, mods: Command, mode: ~Search, action: SearchForward }
  # - { key: B, mods: Command, mode: ~Search, action: SearchBackward }

  #fatih arslan
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: Q, mods: Command, action: Quit }
  - {
      key: N,
      mods: Command,
      command: { program: "open", args: ["-nb", "io.alacritty"] },
    }
  - { key: Home, chars: "\x1bOH", mode: AppCursor }
  - { key: Home, chars: "\x1b[H", mode: ~AppCursor }
  - { key: End, chars: "\x1bOF", mode: AppCursor }
  - { key: End, chars: "\x1b[F", mode: ~AppCursor }
  - { key: Key0, mods: Command, action: ResetFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: PageUp, mods: Shift, chars: "\x1b[5;2~" }
  - { key: PageUp, mods: Control, chars: "\x1b[5;5~" }
  - { key: PageUp, chars: "\x1b[5~" }
  - { key: PageDown, mods: Shift, chars: "\x1b[6;2~" }
  - { key: PageDown, mods: Control, chars: "\x1b[6;5~" }
  - { key: PageDown, chars: "\x1b[6~" }
  - { key: Tab, mods: Shift, chars: "\x1b[Z" }
  - { key: Back, chars: "\x7f" }
  - { key: Back, mods: Alt, chars: "\x1b\x7f" }
  - { key: Insert, chars: "\x1b[2~" }
  - { key: Delete, chars: "\x1b[3~" }
  - { key: Left, mods: Shift, chars: "\x1b[1;2D" }
  - { key: Left, mods: Control, chars: "\x1b[1;5D" }
  - { key: Left, mods: Alt, chars: "\x1b[1;3D" }
  - { key: Left, chars: "\x1b[D", mode: ~AppCursor }
  - { key: Left, chars: "\x1bOD", mode: AppCursor }
  - { key: Right, mods: Shift, chars: "\x1b[1;2C" }
  - { key: Right, mods: Control, chars: "\x1b[1;5C" }
  - { key: Right, mods: Alt, chars: "\x1b[1;3C" }
  - { key: Right, chars: "\x1b[C", mode: ~AppCursor }
  - { key: Right, chars: "\x1bOC", mode: AppCursor }
  - { key: Up, mods: Shift, chars: "\x1b[1;2A" }
  - { key: Up, mods: Control, chars: "\x1b[1;5A" }
  - { key: Up, mods: Alt, chars: "\x1b[1;3A" }
  - { key: Up, chars: "\x1b[A", mode: ~AppCursor }
  - { key: Up, chars: "\x1bOA", mode: AppCursor }
  - { key: Down, mods: Shift, chars: "\x1b[1;2B" }
  - { key: Down, mods: Control, chars: "\x1b[1;5B" }
  - { key: Down, mods: Alt, chars: "\x1b[1;3B" }
  - { key: Down, chars: "\x1b[B", mode: ~AppCursor }
  - { key: Down, chars: "\x1bOB", mode: AppCursor }
  - { key: F1, chars: "\x1bOP" }
  - { key: F2, chars: "\x1bOQ" }
  - { key: F3, chars: "\x1bOR" }
  - { key: F4, chars: "\x1bOS" }
  - { key: F5, chars: "\x1b[15~" }
  - { key: F6, chars: "\x1b[17~" }
  - { key: F7, chars: "\x1b[18~" }
  - { key: F8, chars: "\x1b[19~" }
  - { key: F9, chars: "\x1b[20~" }
  - { key: F10, chars: "\x1b[21~" }
  - { key: F11, chars: "\x1b[23~" }
  - { key: F12, chars: "\x1b[24~" }
  - { key: F1, mods: Shift, chars: "\x1b[1;2P" }
  - { key: F2, mods: Shift, chars: "\x1b[1;2Q" }
  - { key: F3, mods: Shift, chars: "\x1b[1;2R" }
  - { key: F4, mods: Shift, chars: "\x1b[1;2S" }
  - { key: F5, mods: Shift, chars: "\x1b[15;2~" }
  - { key: F6, mods: Shift, chars: "\x1b[17;2~" }
  - { key: F7, mods: Shift, chars: "\x1b[18;2~" }
  - { key: F8, mods: Shift, chars: "\x1b[19;2~" }
  - { key: F9, mods: Shift, chars: "\x1b[20;2~" }
  - { key: F10, mods: Shift, chars: "\x1b[21;2~" }
  - { key: F11, mods: Shift, chars: "\x1b[23;2~" }
  - { key: F12, mods: Shift, chars: "\x1b[24;2~" }
  - { key: F1, mods: Control, chars: "\x1b[1;5P" }
  - { key: F2, mods: Control, chars: "\x1b[1;5Q" }
  - { key: F3, mods: Control, chars: "\x1b[1;5R" }
  - { key: F4, mods: Control, chars: "\x1b[1;5S" }
  - { key: F5, mods: Control, chars: "\x1b[15;5~" }
  - { key: F6, mods: Control, chars: "\x1b[17;5~" }
  - { key: F7, mods: Control, chars: "\x1b[18;5~" }
  - { key: F8, mods: Control, chars: "\x1b[19;5~" }
  - { key: F9, mods: Control, chars: "\x1b[20;5~" }
  - { key: F10, mods: Control, chars: "\x1b[21;5~" }
  - { key: F11, mods: Control, chars: "\x1b[23;5~" }
  - { key: F12, mods: Control, chars: "\x1b[24;5~" }
  - { key: F1, mods: Alt, chars: "\x1b[1;6P" }
  - { key: F2, mods: Alt, chars: "\x1b[1;6Q" }
  - { key: F3, mods: Alt, chars: "\x1b[1;6R" }
  - { key: F4, mods: Alt, chars: "\x1b[1;6S" }
  - { key: F5, mods: Alt, chars: "\x1b[15;6~" }
  - { key: F6, mods: Alt, chars: "\x1b[17;6~" }
  - { key: F7, mods: Alt, chars: "\x1b[18;6~" }
  - { key: F8, mods: Alt, chars: "\x1b[19;6~" }
  - { key: F9, mods: Alt, chars: "\x1b[20;6~" }
  - { key: F10, mods: Alt, chars: "\x1b[21;6~" }
  - { key: F11, mods: Alt, chars: "\x1b[23;6~" }
  - { key: F12, mods: Alt, chars: "\x1b[24;6~" }
  - { key: F1, mods: Command, chars: "\x1b[1;3P" }
  - { key: F2, mods: Command, chars: "\x1b[1;3Q" }
  - { key: F3, mods: Command, chars: "\x1b[1;3R" }
  - { key: F4, mods: Command, chars: "\x1b[1;3S" }
  - { key: F5, mods: Command, chars: "\x1b[15;3~" }
  - { key: F6, mods: Command, chars: "\x1b[17;3~" }
  - { key: F7, mods: Command, chars: "\x1b[18;3~" }
  - { key: F8, mods: Command, chars: "\x1b[19;3~" }
  - { key: F9, mods: Command, chars: "\x1b[20;3~" }
  - { key: F10, mods: Command, chars: "\x1b[21;3~" }
  - { key: F11, mods: Command, chars: "\x1b[23;3~" }
  - { key: F12, mods: Command, chars: "\x1b[24;3~" }
  - { key: D, mods: Command, chars: "\x06\x76" }
  - { key: D, mods: Command|Shift, chars: "\x06\x73" }
  - { key: W, mods: Command, chars: "\x06\x78" }
  - { key: H, mods: Command, chars: "\x06\x68" }
  - { key: J, mods: Command, chars: "\x06\x6a" }
  - { key: K, mods: Command, chars: "\x06\x6b" }
  - { key: L, mods: Command, chars: "\x06\x6c" }
  - { key: T, mods: Command, chars: "\x06\x63" }
  - { key: RBracket, mods: Command|Shift, chars: "\x06\x6e" }
  - { key: LBracket, mods: Command|Shift, chars: "\x06\x70" }
  - { key: Return, mods: Command|Shift, chars: "\x06\x7a" }
  - { key: Key1, mods: Command, chars: "\x06\x31" }
  - { key: Key2, mods: Command, chars: "\x06\x32" }
  - { key: Key3, mods: Command, chars: "\x06\x33" }
  - { key: Key4, mods: Command, chars: "\x06\x34" }
  - { key: Key5, mods: Command, chars: "\x06\x35" }
  - { key: Key6, mods: Command, chars: "\x06\x36" }
  - { key: Key7, mods: Command, chars: "\x06\x37" }
  - { key: Key8, mods: Command, chars: "\x06\x38" }
  - { key: Key9, mods: Command, chars: "\x06\x39" }
  - { key: Left, mods: Command, chars: "\x06\x48" }
  - { key: Down, mods: Command, chars: "\x06\x4a" }
  - { key: Up, mods: Command, chars: "\x06\x4b" }
  - { key: Right, mods: Command, chars: "\x06\x4c" }
  # move word 
  - { key: Right, mods: Control, chars: "\x1BF" }
  - { key: Left,  mods: Control, chars: "\x1BB" }


debug:
  render_timer: false
